# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: R4ndomBits
description: "Shivanshu Singh's Blog"
keywords: "Jekyll, blog, web"
url: http://r4ndombits.me
baseurl: ""

disqus_shortname: "shivnshu"
disqus_site_shortname: "r4ndombit"

# Author settings
author:
  name: Shivanshu Singh
  job: Senior Undergraduate
  bio: "Geek, Programmer and Technology Enthusiast"
  thumb: /images/profile.jpg
  email: shivanshusinghraj@gmail.com
  url: https://r4ndombits.me/
  github: https://github.com/shivnshu
  goodreads: https://www.goodreads.com/shivnshu 
  facebook: https://www.facebook.com/shivnshu
  linkedin: https://www.linkedin.com/in/shivnshu/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
